server:
  port: 9999
app:
  api-prefix: /api/v1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2